### ISSUE TITLE
Make .j2. hack go away

### ISSUE THREAD

**Issue by spanezz** [spanezz/staticsite#32]
Currently the `.j2.` marker in file names is used to distinguish static assets from jinja2 templates.

Now that we have [directory metadata](https://github.com/spanezz/staticsite/blob/master/doc/contents.md#directory-metadata), we potentially have a way to tell the [j2 feature](https://github.com/spanezz/staticsite/blob/master/staticsite/features/j2.py) a list or glob of files to read as templates regardless of their name.

For example, a `.staticsite` file could have a way to pass information to features:

```yaml
features:
   j2:
      files: [*.html]
```

this seems rather verbose. Alternatively, allow `files` to be a glob, and use its metadata to communicate with features:

```yaml
files:
   *.html:
      feature: jinja2
```

this sounds flexible but not really straightforward. Another option can be to say that if one provides extra metadata for a `.html` file, then the j2 feature would automatically consider it a template:

```yaml
files:
   index.html:
      title: "Enrico's interesting site"
```

And if in the future this causes static assets to be wrongly interpreted as templates, one could easily add a `static: yes` metadata to disable it on a file by file basis.
